# Generated by Django 5.0.6 on 2024-05-21 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='networknode',
            options={'verbose_name': 'Узел сети', 'verbose_name_plural': 'Узлы сети'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='networknode',
            name='city',
            field=models.CharField(max_length=255, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='country',
            field=models.CharField(max_length=255, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='debt_to_supplier',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Задолженность'),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='house_number',
            field=models.CharField(max_length=10, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='street',
            field=models.CharField(max_length=255, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.networknode', verbose_name='Поставщик'),
        ),
    ]
