# Generated by Django 5.0.6 on 2024-05-29 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_product_model_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='networknode',
            options={},
        ),
        migrations.AddField(
            model_name='networknode',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Factory'), (1, 'Retail Network'), (2, 'Individual Entrepreneur')], default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='debt_to_supplier',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='house_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='street',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='network.networknode'),
        ),
    ]
